### ISSUE TITLE
new player

### ISSUE THREAD

**Issue by B4ngB4ng** [MrEliasen/Supremacy-Framework#4] opened 2015-08-18 14:20 UTC
spmc_players (p_steam64, p_money, p_name, p_joindate, p_lastactive)

 Field 'p_stats' doesn't have a default value

p_stats needs a default value or has to be null also the equipment will not be saved !

**Comment by MrEliasen** [comment] 2015-08-18 16:49
The gear will save a couple of seconds after leaving a shop or every 10-15 mins. I can add a simple player menu to manually "force" a save.

The p_starts is a textfield and should not need a default value. Is it causing an issue somewhere or what is giving you that error?

Thanks for opening the issue, will look into the saving right away and let me know about the "default value" and whether you believe the gear should have saved still when taking the above mentioned info into consideration.

**Comment by MrEliasen** [comment] 2015-08-18 20:34
I have pushed update 0.3.1 which adds a player menu where you can initiate a manual full sync. Let me know this is solves your issue. I just tried the automatic sync and it seems to work just fine, but if you are having issues then of cause something is not working as intended :).

Thanks again for the heads up.

**Comment by B4ngB4ng** [comment] 2015-08-19 07:35
hey thank you. Great work BTW  :+1: 

There is a sql file with "`p_stats` varchar(20) NOT NULL," also "`p_equipment` text NOT NULL,"

but int the 

spmc.ini 

[newPlayer]
"SQL1_2 =     spmc_players (p_steam64, p_money, p_name, p_joindate, p_lastactive)" 

that is not working in my case because the database needs to have a value at p_stats and p_equipment

also is it only working if i put the spmc.ini in @extDB2\extDB\sql_custom_v2

i really like the framework its a great IDEA to make custom Mods

**Comment by MrEliasen** [comment] 2015-08-19 07:40
Ahh! Sorry I understand what you mean now - I'll push a fix for this later today :).

Thanks! Yea it really is just meant as a platform to add your own stuff and make your own custom settings. Glad you like it.

**Comment by MrEliasen** [comment] 2015-08-19 11:38
This should now be fixed, along with some other bits. Thanks again for bringing it to my attention!

**Closed by MrEliasen** 2015-08-19 11:38 UTC
Labels: bug
